#!/usr/bin/env bash

# TODO: This should be a non-bash file, and not set any bash-specific options

[ -z $TMP ] && stat "/tmp" > /dev/null && export TMP="/tmp"

test -f ${HOME}/dotfiles/helpers        && source ${HOME}/dotfiles/helpers
test -f ${HOME}/dev/dotfiles/helpers    && source ${HOME}/dev/dotfiles/helpers

verbose "---------- profile-plus start"

if ! [[ $OS =~ Windows ]]; then
  test -d /tmp && sudo chmod 777 /tmp
fi

export EDITOR="vim"
export VISUAL="vim"

export JSAWS_AWS_ACCT_EXTRA_CREDS="pub:244406501905/mario-mobilewebprint,panini:311778409164/mario-mobilewebprint,dev"
export JSAWS_AWS_ACCTS="pub:244406501905,panini:311778409164,dev:084075158741"
export REF_ID="884AB755-720C-4B64-BAB5-23C279AEBB65"

#if cut -d: -f1 /etc/passwd | egrep '^mongodb$'; then
#  sudo chown mongodb:mongodb /data
#fi

# set PATH so it includes user's private bin if it exists
[ -d "$HOME/bin" ]            && PATH="$HOME/bin:$PATH"
[ -d "$HOME/local/bin" ]      && PATH="$HOME/local/bin:$PATH"

# Include dotfileses binaries in PATH
[ -d "$HOME/dotfiles" ]       && PATH="$PATH:${HOME}/dotfiles/bin"
[ -d "$HOME/dev/dotfiles" ]   && PATH="$PATH:${HOME}/dev/dotfiles/bin"

# Include bridge47 scripts in PATH
[[ -d "$HOME/dev/bridge47/admin"      ]] && PATH="$PATH:$HOME/dev/bridge47/admin"
[[ -d "$HOME/dev/b/bridge47/admin"    ]] && PATH="$PATH:$HOME/dev/b/bridge47/admin"

# Include js-cluster scripts in PATH
[[ -d "$HOME/dev/js-cluster/scripts"        ]] && PATH="$PATH:$HOME/dev/js-cluster/scripts"
[[ -d "$HOME/dev/b/js-cluster/scripts"      ]] && PATH="$PATH:$HOME/dev/b/js-cluster/scripts"

# Include serverassist scripts in PATH
[[ -d "$HOME/dev/serverassist/scripts"      ]] && PATH="$PATH:$HOME/dev/serverassist/scripts"
[[ -d "$HOME/dev/b/serverassist/scripts"    ]] && PATH="$PATH:$HOME/dev/b/serverassist/scripts"

# Include server-assist-server scripts in PATH
[[ -d "$HOME/dev/server-assist-server/webtier/scripts"      ]] && PATH="$PATH:$HOME/dev/server-assist-server/webtier/scripts"
[[ -d "$HOME/dev/b/server-assist-server/webtier/scripts"    ]] && PATH="$PATH:$HOME/dev/b/server-assist-server/webtier/scripts"

# Include mario-util scripts in PATH
[[ -d "$HOME/dev/mario-util/admin/scripts"      ]] && PATH="$PATH:$HOME/dev/mario-util/admin/scripts"
[[ -d "$HOME/dev/b/mario-util/admin/scripts"    ]] && PATH="$PATH:$HOME/dev/b/mario-util/admin/scripts"

#Mario
[ -d "$HOME/dev/mario_util/admin" ] && PATH="$PATH:$HOME/dev/mario_util/admin"

[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

# krew is a k8s utility to install kubectl add-ons
export PATH="$HOME/.krew/bin:$PATH"

# Linuxbrew
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)



verbose "---------- profile-plus end"

