#!/usr/bin/env bash

test -f ${HOME}/dotfiles/helpers        && source ${HOME}/dotfiles/helpers
test -f ${HOME}/dev/dotfiles/helpers    && source ${HOME}/dev/dotfiles/helpers

verbose "---------- profile-plus start"

test -d /tmp && sudo chmod 777 /tmp

export JSAWS_AWS_ACCT_EXTRA_CREDS="pub:244406501905/mario-mobilewebprint,panini:311778409164/mario-mobilewebprint,dev"

#if cut -d: -f1 /etc/passwd | egrep '^mongodb$'; then
#  sudo chown mongodb:mongodb /data
#fi

# set PATH so it includes user's private bin if it exists
[ -d "$HOME/bin" ]            && PATH="$HOME/bin:$PATH"
[ -d "$HOME/local/bin" ]      && PATH="$HOME/local/bin:$PATH"

# Include dotfileses binaries
[ -d "$HOME/dotfiles" ]       && PATH="$PATH:${HOME}/dotfiles/bin"
[ -d "$HOME/dev/dotfiles" ]   && PATH="$PATH:${HOME}/dev/dotfiles/bin"

# Include js-cluster scripts
[[ -d "$HOME/dev/js-cluster/scripts"   ]] && PATH="$PATH:$HOME/dev/js-cluster/scripts"
[[ -d "$HOME/dev/serverassist/scripts" ]] && PATH="$PATH:$HOME/dev/serverassist/scripts"

#Mario
[ -d "$HOME/dev/mario_util/admin" ] && PATH="$PATH:$HOME/dev/mario_util/admin"

[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion

verbose "---------- profile-plus end"

