#!/usr/bin/env bash

RESET="\[\017\]"
NORMAL="\[\033[0m\]"
BOLD="\[\033[1m\]"
RED="\[\033[31m\]"
REDBOLD="\[\033[31;1m\]"
GREEN="\[\033[32m\]"
GREENBOLD="\[\033[32;1m\]"
YELLOW="\[\033[33m\]"
BLUE="\[\033[34m\]"
BLUEBOLD="\[\033[35;1m\]"
WHITE="\[\033[37m\]"
WHITEBOLD="\[\033[37;1m\]"
BLACK="\[\033[30m\]"
BLACKBOLD="\[\033[30;1m\]"

# No such colors:
#YELLOWBOLD="\[\033[33;1m\]"

# What is the git status?
__gs() {
  if git branch 2> /dev/null; then
    local b=$(git branch | grep '^\*' | grep -o '[^ ]*$')
    local mod=$(git status --short | wc -l | tr -d ' ')
    local new=$(git ls-files -o --exclude-standard | wc -l | tr -d ' ')

    if [[ $new > 0 ]]; then
      b="$b+"
    fi

    if [[ $mod > 0 ]]; then
        b="$b*"
        [[ $mod > 1 ]] && b="$b*"
        [[ $mod > 2 ]] && b="$b*"
        [[ $mod > 3 ]] && b="$b*"
        [[ $mod > 4 ]] && b="$b*"
        [[ $mod > 5 ]] && b="$b ($mod)"
    fi

    echo " [$b]"
  fi
}

GS="__gs | tail -1"

# Get the proxy
__gproxy() {
  echo $http_proxy | sed 's/http:\/\///g; s/:[0-9]*//g; s/\/$//g; s/proxy//g; s/hp\.com//g; s/\.//g'
}

GPROXY="__gproxy | tail -1"

test -f $HOME/mario_env && source $HOME/mario_env
[[ "$MARIO_STACK_NAME" =~ "pub" ]] && export PROMPT_WARNING="this-is-a-prod-server-"

SMILEY="${WHITE}:)${NORMAL}"
FROWNY="${REDBOLD}:(${NORMAL}"
SELECT="if [ \$? = 0 ]; then echo \"${SMILEY}\"; else echo \"${FROWNY}\"; fi"
WARNING="test -n ${PROMPT_WARNING} && echo \"${REDBOLD}${PROMPT_WARNING}\""

# Throw it all together
if [ "$USER" = "sparksb" ]
then
  #PS1="${RESET}${BLUEBOLD}\h:\w${NORMAL} (\$(__gs)) \`${SELECT}\` ${YELLOW}\n\$${NORMAL} "
  #PS1="${RESET}${BLUE}[\t] ${BLUEBOLD}\h\$(__gs | tail -1):\w${NORMAL} \`${SELECT}\` ${YELLOW}\n\$${NORMAL} "
  PS1="${RESET}${BLUE}[\t] \`${SELECT}\` ${BLUEBOLD}\h\`${GS}\`[\`${GPROXY}\`]:\w${NORMAL} ${YELLOW}\n\$${NORMAL} "
  #    ^^ host:dir ^^^^^^^^^^^^^^^^^ ^^ smiley ^^^ ^^ $ ^^^^^^^^^^^^^^^^^
elif [ "$USER" = "scotty" ]
then
  PS1="${RESET}${BLUE}[\t]  \`${SELECT}\` ${YELLOW}\h\`${GS}\`:\w${NORMAL}\n\`${WARNING}\`${YELLOW}\$${NORMAL} "
elif [ "$USER" = "dagwood" ]
then
  PS1="${RESET}${BLUE}[\t] ${RED}${SG_PROMPT_PREFIX}-${YELLOW}\u\`${GS}\`:\w${NORMAL} \`${SELECT}\` ${YELLOW}\n\$${NORMAL} "
elif [ "$USER" = "ubuntu" ]
then
  PS1="${RESET}${BLUE}[\t] ${RED}${SG_PROMPT_PREFIX}-${YELLOW}\u\`${GS}\`:\w${NORMAL} \`${SELECT}\` ${YELLOW}\n\$${NORMAL} "
fi

if [[ -n $MARIO_STACK && -n $MARIO_COLOR && -n $MARIO_SERVICE ]]; then
  PS1="${RESET}${BLUE}[\t]  \`${SELECT}\` ${YELLOW}${MARIO_COLOR}-${MARIO_STACK}-${MARIO_SERVICE} \h\`${GS}\`:\w${NORMAL}\n\`${WARNING}\`${YELLOW}\$${NORMAL} "
fi

