#!/bin/bash -e

for f in $(ls dot); do
  test -f ../.${f} || ln -s "dotfiles/dot/$f" "../.$f"
done

# VIM setup
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -SLso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
cd ~/.vim/bundle
git clone https://github.com/vim-ctrlspace/vim-ctrlspace.git
cd

