#!/bin/bash

# TODO: remove bash-isms (***)

pathogen()
{
  git_user="$1"
  module="$2"

  # (***)
  if ! [[ -d ~/.vim/bundle/${module} ]]; then
    (cd ~/.vim/bundle && git clone --depth=1 https://github.com/${git_user}/${module}.git)
  fi
}

for f in $(ls dot); do
  # (***)
  test -f ../.${f} || ln -s "dotfiles/dot/$f" "../.$f"
done

# Development
npm install -g eslint babel-eslint eslint-plugin-react underscore-cli yarn || \
    sudo npm install -g eslint babel-eslint eslint-plugin-react underscore-cli yarn

if which apt-get > /dev/null; then
  sudo apt-get install -y silversearcher-ag curl socat tree htop jq parallel nmap git mercurial gawk \
      subversion cscope exuberant-ctags realpath unzip zip graphviz dos2unix
else
  echo "Install silversearcher-ag curl socat tree htop jq parallel nmap git mercurial gawk subversion cscope exuberant-ctags realpath unzip zip graphviz dos2unix"
fi

# VIM setup
mkdir -p ~/.vim/autoload ~/.vim/bundle

# (***)
test -f ~/.vim/autoload/pathogen.vim || curl -SLso ~/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim




pathogen vim-ctrlspace vim-ctrlspace
pathogen scrooloose syntastic
pathogen mxw vim-jsx
pathogen pangloss vim-javascript
pathogen rust-lang rust.vim
pathogen kballard vim-swift
pathogen tpope vim-markdown
pathogen jneen ragel.vim
pathogen chr4 nginx.vim
pathogen qualiabyte vim-colorstepper

# vim-javascript and vim-jsx do horrible indentation
# (***)
if [[ -d ~/.vim/bundle/vim-javascript/indent ]]; then
  rm -rf ~/.vim/bundle/vim-javascript/indent
  rm -f ~/.vim/bundle/vim-jsx/after/indent/jsx.vim
fi

# TODO: only for Linux
# Linuxbrew, fzf / ntl
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
#
# TODO: once we can install and use brew in one fell swoop, do this:
#$(brew --prefix)/opt/fzf/install


cd

# vim: ft=bash:

