execute pathogen#infect()

:let mapleader = ","

:set nocompatible
:set hidden
:set showcmd
:set nu
:syntax on
:set ruler
":set autoread
highlight StatusLine ctermfg=blue ctermbg=yellow

filetype plugin indent on

" Show error whitespace
highlight ErrorWhitespace ctermbg=red guibg=red
match ErrorWhitespace /\s\+$/
autocmd BufWinEnter * match ErrorWhitespace /\s\+$/
autocmd InsertEnter * match ErrorWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ErrorWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
autocmd ColorScheme * highlight ErrorWhitespace ctermbg=red guibg=red

":set background=dark
"let g:solarized_termcolors=256
"colorscheme solarized

" Whitespace
:set nowrap
:set tabstop=2
:set shiftwidth=2
:set expandtab
:set smartindent
:set backspace=indent,eol,start

" Searching
:set hlsearch
:set incsearch
:set ignorecase
:set smartcase

:set noswapfile

:set path=./**

"
" --------------- key mappings ----------------
"

" Next / Previous tab
:map <F7> :tabp<CR>
:map <F8> :tabn<CR>

" Open new tab
:map <C-t> <esc>:tabe<CR>,t

" Next and previous error (quickfix)
:map <C-n> :cn<CR>
:map <C-p> :cp<CR>

" Open file from the same dir
:map <Leader>e :e <C-R>=expand("%:p:h") . '/'<CR>

" Clear search
nmap <silent> ,. :nohlsearch<CR>

:color desert

" :source ~/zz_packages/vim/runtime/macros/matchit.vim

let g:ackprg="/usr/local/bin/ack -H --nocolor --column"
" Lets see if we like these

"
" ------------------------------------- vim-javascript  --------------------------------------------------
"
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1

"
" ------------------------------------- vim-jsx  --------------------------------------------------
"
let g:jsx_ext_required = 0 " Allow JSX in normal JS files

"
" ------------------------------------- Syntastic  --------------------------------------------------
"
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { 'mode' : 'active',
                           \ 'passive_filetypes' : ['java', 'cpp', 'objc'] }

let g:syntastic_html_tidy_ignore_errors=[" proprietary attribute " ,"trimming empty <", "unescaped &" , "lacks \"action", "is not recognized!", "discarding unexpected"]
let g:syntaxtic_javascript_checkers=['eslint']

" ------------------------------------- rails.vim  --------------------------------------------------
"
" Set up some useful Rails.vim bindings for working with Backbone.js
autocmd User Rails Rnavcommand template    app/assets/templates                 -glob=**/*  -suffix=.jst.ejs
autocmd User Rails Rnavcommand jmodel      app/assets/javascripts/models        -glob=**/*  -suffix=.js
autocmd User Rails Rnavcommand jview       app/assets/javascripts/views         -glob=**/*  -suffix=.js
autocmd User Rails Rnavcommand jcollection app/assets/javascripts/collections   -glob=**/*  -suffix=.js
autocmd User Rails Rnavcommand jrouter     app/assets/javascripts/routers       -glob=**/*  -suffix=.js
autocmd User Rails Rnavcommand jspec       spec/javascripts                     -glob=**/*  -suffix=.js

"
" ------------------------------------- vim-ctrlspace  --------------------------------------------------
"
hi CtrlSpaceSelected term=reverse ctermfg=187  ctermbg=23  cterm=bold
hi CtrlSpaceNormal   term=NONE    ctermfg=244  ctermbg=232 cterm=NONE
hi CtrlSpaceSearch   ctermfg=220  ctermbg=NONE cterm=bold
hi CtrlSpaceStatus   ctermfg=230  ctermbg=234  cterm=NONE

let g:ctrlspace_load_last_workspace_on_start=1
let g:ctrlspace_save_workspace_on_exit=1

let g:ctrlspace_glob_command = 'git ls-files -o --exclude-standard -c "" | egrep -v "^archive/loki"'
let g:ctrlspace_max_files=0
let g:ctrlspace_max_search_results=0

" vim-ctrlspace v5
let g:CtrlSpaceSaveWorkspaceOnSwitch = 1
let g:CtrlSpaceSaveWorkspaceOnExit = 1

if executable("ag")
  let g:CtrlSpaceGlobCommand = 'ag -l --nocolor -g ""'
endif

vnoremap // y/<C-R>"<CR>

